spring:
  data:
    mongodb:
      username: admin
      password: password
      host: localhost
      port: 27017
      database: product-service
      authentication-database: admin

server:
  port: 8088
